---
- name: Test execution 
  hosts: all
  become: false # privilege escalation
  gather_facts: no # no collection of facts / info about remote hosts 
  vars: 
    - fileLocation: C:\Temp\TempFolder\
    - backupZipFile: backupzipfile.zip
    - exportedBackupFile: backupzipfile.printerExport
    - printerTool: c:\windows\system32\spool\tools\PrintBrm.exe
    - downloadServer: \\server\downloaddirectory

# tasks / commands to be executed 
  tasks: 
    - name: Ping test to verify connection to targets 
      win_ping: 
    - name: Make sure Print and Document is configured on the server
      ansible.windows.win_feature: 
        name: Print-Services
        state: present
    - name: Create test folder
      ansible.windows.win_file: 
        path: '{{ fileLocation }}'
        state: directory 
    # copy from windows share to target VM not working 
    # - name: Copy file from share using PS # not working
    #   ansible.windows.win_shell: |
    #     wget "{{ downloadServer }}{{ backupZipFile }}"
    # - name: Copy file from share
    #   ansible.windows.win_shell: |
    #     copy "{{ downloadServer }}{{ backupZipFile }}" "{{ fileLocation }}"
    - name: Copy file from share using win_copy
      ansible.windows.win_copy:
        src: "{{ downloadServer }}{{ backupZipFile }}"
        dest: "{{ fileLocation }}"
        remote_src: yes 
      vars: 
        become: yes
        become_user: admin-account
    - name: Extract backup file into script folder 
      ansible.windows.win_shell: Expand-Archive "{{ fileLocation }}{{ backupZipFile }}" -DestinationPath "{{ fileLocation }}"
    - name: Run backup script to restore print server
      ansible.windows.win_shell: |
        {{ printerTool }} -R -P ORIG -F "{{ fileLocation }}{{ exportedBackupFile }}"